[package]
name = "rsmlui"
version = "0.1.0"
edition = "2024"

[dependencies]
rsmlui-sys = { path = "../rsmlui-sys", default-features = false }
drop-tree = { path = "../drop-tree" }

glam = "0.30.9"
thiserror = "2.0.17"

[features]
default = ["freetype"]

cosmic-text = ["rsmlui-sys/cosmic-text"]
freetype = ["rsmlui-sys/freetype"]

system-win32 = ["rsmlui-sys/system-win32"]
renderer-gl2 = ["rsmlui-sys/renderer-gl2"]

backend-win32-gl2 = ["system-win32", "renderer-gl2"]
